#!/usr/bin/env python3
"""Convert a .tflite model into the C source embedded by the firmware.

Generates main/model/model_data.cc with the model bytes so the firmware can
embed the model in flash. After running this, set BIRDNET_HAS_REAL_MODEL to 1
(in main/birdnet_config.h or via -DBIRDNET_HAS_REAL_MODEL=1) and rebuild.

Usage:
    python tools/convert_model.py path/to/model.tflite [output.cc]

If the output path is omitted, main/model/model_data.cc is overwritten.
"""
import os
import sys

HEADER = """\
/**
 * @file model_data.cc
 * @brief Embedded TFLite model byte array (generated by tools/convert_model.py).
 *
 * Do not edit by hand. Regenerate with:
 *   python tools/convert_model.py <model.tflite> main/model/model_data.cc
 */
#include "model_data.h"

alignas(16) const unsigned char birdnet_model_tflite[] = {
"""

FOOTER = """\
}};

const unsigned int birdnet_model_tflite_len =
    (unsigned int)sizeof(birdnet_model_tflite);
"""


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 1

    tflite_path = argv[1]
    if not os.path.isfile(tflite_path):
        print(f"error: model not found: {tflite_path}", file=sys.stderr)
        return 1

    if len(argv) >= 3:
        out_path = argv[2]
    else:
        here = os.path.dirname(os.path.abspath(__file__))
        out_path = os.path.join(here, "..", "main", "model", "model_data.cc")
    out_path = os.path.abspath(out_path)

    with open(tflite_path, "rb") as f:
        data = f.read()

    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())

    with open(out_path, "w", newline="\n") as f:
        f.write(HEADER)
        f.write("\n".join(lines))
        f.write("\n")
        f.write(FOOTER)

    print(f"Wrote {len(data)} bytes -> {out_path}")
    print("Next: set BIRDNET_HAS_REAL_MODEL=1 and rebuild (idf.py build).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
